//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/AppInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace ShapeReality
{
    public partial class @AppInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @AppInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""AppInput"",
    ""maps"": [
        {
            ""name"": ""LeftHand"",
            ""id"": ""49c89128-926e-4615-9ea6-d146629b0e00"",
            ""actions"": [
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""0c26715b-1bd7-49d6-8575-062aee127619"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerDown"",
                    ""type"": ""Button"",
                    ""id"": ""6b75e97f-e275-450c-93f4-bcc2fa2c536e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerUp"",
                    ""type"": ""Button"",
                    ""id"": ""2038ce2a-ea90-4891-82f0-ca2e6f4563b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3a895f4-d950-4175-992b-6d526b9f1e71"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19aa2d11-40bd-40d2-b84d-019ce06dfa3d"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e17fa71-ffed-401c-813c-5d2610a9ebd0"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa8c5443-bc5f-4e97-9300-10bcc4f310c4"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8305490b-b72b-4e8b-98b1-3a169f9456a3"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04a8fb14-126c-4a27-9288-859961c98a56"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightHand"",
            ""id"": ""5b62d2b5-9bc7-442e-987c-501e86f5c6b6"",
            ""actions"": [
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""c5eabf96-96d1-4047-98cc-aa12ffcc9dce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerDown"",
                    ""type"": ""Button"",
                    ""id"": ""d64df517-4adf-4b33-a485-05df7233a310"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerUp"",
                    ""type"": ""Button"",
                    ""id"": ""67b53055-10b1-44d1-a83a-ddc4621dcd98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7da5e4c1-1e04-46e5-a48c-6c680112f5ff"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d889731-aced-41b2-96bc-c66069ad6a6d"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ea59164-f697-4296-8ef5-1a62b1d9ab1a"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6f47040-b68f-4943-bc08-dfd41f8c87ec"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24cf2732-ea82-4444-b394-a2750015ec49"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7889bba-5740-4421-84b0-99e4900538c2"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Generic XR Controller"",
                    ""action"": ""PointerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Generic XR Controller"",
            ""bindingGroup"": ""Generic XR Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // LeftHand
            m_LeftHand = asset.FindActionMap("LeftHand", throwIfNotFound: true);
            m_LeftHand_ToggleMenu = m_LeftHand.FindAction("ToggleMenu", throwIfNotFound: true);
            m_LeftHand_PointerDown = m_LeftHand.FindAction("PointerDown", throwIfNotFound: true);
            m_LeftHand_PointerUp = m_LeftHand.FindAction("PointerUp", throwIfNotFound: true);
            // RightHand
            m_RightHand = asset.FindActionMap("RightHand", throwIfNotFound: true);
            m_RightHand_ToggleMenu = m_RightHand.FindAction("ToggleMenu", throwIfNotFound: true);
            m_RightHand_PointerDown = m_RightHand.FindAction("PointerDown", throwIfNotFound: true);
            m_RightHand_PointerUp = m_RightHand.FindAction("PointerUp", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // LeftHand
        private readonly InputActionMap m_LeftHand;
        private ILeftHandActions m_LeftHandActionsCallbackInterface;
        private readonly InputAction m_LeftHand_ToggleMenu;
        private readonly InputAction m_LeftHand_PointerDown;
        private readonly InputAction m_LeftHand_PointerUp;
        public struct LeftHandActions
        {
            private @AppInput m_Wrapper;
            public LeftHandActions(@AppInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @ToggleMenu => m_Wrapper.m_LeftHand_ToggleMenu;
            public InputAction @PointerDown => m_Wrapper.m_LeftHand_PointerDown;
            public InputAction @PointerUp => m_Wrapper.m_LeftHand_PointerUp;
            public InputActionMap Get() { return m_Wrapper.m_LeftHand; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LeftHandActions set) { return set.Get(); }
            public void SetCallbacks(ILeftHandActions instance)
            {
                if (m_Wrapper.m_LeftHandActionsCallbackInterface != null)
                {
                    @ToggleMenu.started -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnToggleMenu;
                    @ToggleMenu.performed -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnToggleMenu;
                    @ToggleMenu.canceled -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnToggleMenu;
                    @PointerDown.started -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnPointerDown;
                    @PointerDown.performed -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnPointerDown;
                    @PointerDown.canceled -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnPointerDown;
                    @PointerUp.started -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnPointerUp;
                    @PointerUp.performed -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnPointerUp;
                    @PointerUp.canceled -= m_Wrapper.m_LeftHandActionsCallbackInterface.OnPointerUp;
                }
                m_Wrapper.m_LeftHandActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ToggleMenu.started += instance.OnToggleMenu;
                    @ToggleMenu.performed += instance.OnToggleMenu;
                    @ToggleMenu.canceled += instance.OnToggleMenu;
                    @PointerDown.started += instance.OnPointerDown;
                    @PointerDown.performed += instance.OnPointerDown;
                    @PointerDown.canceled += instance.OnPointerDown;
                    @PointerUp.started += instance.OnPointerUp;
                    @PointerUp.performed += instance.OnPointerUp;
                    @PointerUp.canceled += instance.OnPointerUp;
                }
            }
        }
        public LeftHandActions @LeftHand => new LeftHandActions(this);

        // RightHand
        private readonly InputActionMap m_RightHand;
        private IRightHandActions m_RightHandActionsCallbackInterface;
        private readonly InputAction m_RightHand_ToggleMenu;
        private readonly InputAction m_RightHand_PointerDown;
        private readonly InputAction m_RightHand_PointerUp;
        public struct RightHandActions
        {
            private @AppInput m_Wrapper;
            public RightHandActions(@AppInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @ToggleMenu => m_Wrapper.m_RightHand_ToggleMenu;
            public InputAction @PointerDown => m_Wrapper.m_RightHand_PointerDown;
            public InputAction @PointerUp => m_Wrapper.m_RightHand_PointerUp;
            public InputActionMap Get() { return m_Wrapper.m_RightHand; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(RightHandActions set) { return set.Get(); }
            public void SetCallbacks(IRightHandActions instance)
            {
                if (m_Wrapper.m_RightHandActionsCallbackInterface != null)
                {
                    @ToggleMenu.started -= m_Wrapper.m_RightHandActionsCallbackInterface.OnToggleMenu;
                    @ToggleMenu.performed -= m_Wrapper.m_RightHandActionsCallbackInterface.OnToggleMenu;
                    @ToggleMenu.canceled -= m_Wrapper.m_RightHandActionsCallbackInterface.OnToggleMenu;
                    @PointerDown.started -= m_Wrapper.m_RightHandActionsCallbackInterface.OnPointerDown;
                    @PointerDown.performed -= m_Wrapper.m_RightHandActionsCallbackInterface.OnPointerDown;
                    @PointerDown.canceled -= m_Wrapper.m_RightHandActionsCallbackInterface.OnPointerDown;
                    @PointerUp.started -= m_Wrapper.m_RightHandActionsCallbackInterface.OnPointerUp;
                    @PointerUp.performed -= m_Wrapper.m_RightHandActionsCallbackInterface.OnPointerUp;
                    @PointerUp.canceled -= m_Wrapper.m_RightHandActionsCallbackInterface.OnPointerUp;
                }
                m_Wrapper.m_RightHandActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ToggleMenu.started += instance.OnToggleMenu;
                    @ToggleMenu.performed += instance.OnToggleMenu;
                    @ToggleMenu.canceled += instance.OnToggleMenu;
                    @PointerDown.started += instance.OnPointerDown;
                    @PointerDown.performed += instance.OnPointerDown;
                    @PointerDown.canceled += instance.OnPointerDown;
                    @PointerUp.started += instance.OnPointerUp;
                    @PointerUp.performed += instance.OnPointerUp;
                    @PointerUp.canceled += instance.OnPointerUp;
                }
            }
        }
        public RightHandActions @RightHand => new RightHandActions(this);
        private int m_GenericXRControllerSchemeIndex = -1;
        public InputControlScheme GenericXRControllerScheme
        {
            get
            {
                if (m_GenericXRControllerSchemeIndex == -1) m_GenericXRControllerSchemeIndex = asset.FindControlSchemeIndex("Generic XR Controller");
                return asset.controlSchemes[m_GenericXRControllerSchemeIndex];
            }
        }
        public interface ILeftHandActions
        {
            void OnToggleMenu(InputAction.CallbackContext context);
            void OnPointerDown(InputAction.CallbackContext context);
            void OnPointerUp(InputAction.CallbackContext context);
        }
        public interface IRightHandActions
        {
            void OnToggleMenu(InputAction.CallbackContext context);
            void OnPointerDown(InputAction.CallbackContext context);
            void OnPointerUp(InputAction.CallbackContext context);
        }
    }
}
